#!/bin/sh

if [ "$1" = remove ] && command -v systemctl >/dev/null 2>&1; then
	systemctl disable --now smartdns-geosite-update.timer || true
	systemctl disable --now smartdns-cloudflare-speedtest.timer || true
	systemctl disable --now smartdns.service || true
fi
